service: notes-api
frameworkVersion: "2"

provider:
  name: aws
<<<<<<< HEAD
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  authorizer:
    handler: authorizer.handler
    environment:
      COGNITO_USERPOOL_ID: !Ref cognitoUserPool
      COGNITO_WEB_CLIENT_ID: !Ref cognitoUserPoolWebclient
=======
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  authorizer: 
    handler: authorizer.handler
>>>>>>> 8cda0279fdedfe04d20701b4690d42b1a9d4f56e

  createNote:
    handler: handler.createNote
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: post
          path: notes
          authorizer: authorizer

  updateNote:
    handler: handler.updateNote
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: put
          path: notes/{id}
<<<<<<< HEAD
          # authorizer: authorizer
=======
          authorizer: authorizer
>>>>>>> 8cda0279fdedfe04d20701b4690d42b1a9d4f56e

  deleteNote:
    handler: handler.deleteNote
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: delete
          path: notes/{id}
          authorizer: authorizer

  getAllNotes:
    handler: handler.getAllNotes
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: !GetAtt notesTable.Arn
    events:
      - http:
          method: get
          path: notes
<<<<<<< HEAD
          authorizer:
            name: userpool_authorizer
            arn: ${ssm:/notes/${self:provider.stage}/userPoolArn}
=======
          authorizer: authorizer
>>>>>>> 8cda0279fdedfe04d20701b4690d42b1a9d4f56e

plugins:
  - serverless-iam-roles-per-function

# you can add CloudFormation resource templates here
resources:
<<<<<<< HEAD
  Resources: ${file(resources.yml)}
=======
  Resources:
    notesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: notesId
            AttributeType: S
        KeySchema:
          - AttributeName: notesId
            KeyType: HASH
>>>>>>> 8cda0279fdedfe04d20701b4690d42b1a9d4f56e
